components:
  schemas:
    ProductTop:
      type: object
      properties:
        id:
          type: integer
          example: 101
          description: ID của sản phẩm
        title:
          type: string
          example: 'iPhone 16 Pro Max'
          description: Tên sản phẩm
        sku:
          type: string
          example: 'IPH16PMAX256'
          description: Mã SKU của sản phẩm
        thumb:
          type: string
          format: uri
          example: 'https://cdn.pinkcapy.vn/products/iphone16pro-thumb.jpg'
          description: Ảnh thumbnail của sản phẩm
        sold:
          type: integer
          example: 74
          description: Tổng số lượng đã bán
        revenue:
          type: number
          format: double
          example: 2590000000
          description: Tổng doanh thu mang lại từ sản phẩm
        category:
          type: string
          example: 'Smartphone'
          description: Danh mục chính của sản phẩm
        status:
          type: string
          enum: [draft, published, archived]
          example: 'published'
          description: Trạng thái hiển thị của sản phẩm
      required:
        - id
        - title
        - sold
        - revenue
