paths:
  /products/{id}:
    get:
      summary: Get product
      description: Retrieve a product by its ID.
      tags: [Product]
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../components/schemas/core/response.yaml'
                  - type: object
                    properties:
                      data:
                        $ref: '../components/schemas/product/product_public.yaml'
        '404':
          $ref: '../components/responses/error.yaml#/NotFound'

  /products:
    get:
      summary: Search products
      description: Retrieve a list of products based on search criteria.
      tags: [Product]
      parameters:
        - name: offset
          in: query
          required: true
          description: Currect offset to retrieve
          default: 1
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: true
          description: Limit number of results
          default: 10
          schema:
            type: integer
            example: 10
        - name: sort
          in: query
          description: Sort order
          schema:
            type: string
            format: '<sortable_criteria>:<order>'
            example: 'created_at:desc'
        - name: query
          in: query
          description: Search keyword
          schema:
            type: string
            example: 'tai nghe'
        - name: category
          in: query
          description: Category ID of the products
          schema:
            type: integer
            example: 3
        - name: price_min
          in: query
          description: Minimum price of the products
          schema:
            type: integer
            example: 100000
        - name: price_max
          in: query
          description: Maximum price of the products
          schema:
            type: integer
            example: 500000
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../components/schemas/core/response.yaml'
                  - type: object
                    properties:
                      data:
                        allOf:
                          - $ref: '../components/schemas/core/infinite_response.yaml'
                          - type: object
                            properties:
                              data:
                                items:
                                  $ref: '../components/schemas/product/product_public.yaml'
