meta: &meta
  $ref: '../../../openapi.yaml#/components/schemas/Meta'
infinite_scroll: &infinite_scroll
  $ref: '../../../openapi.yaml#/components/schemas/InfiniteScroll'
offset_param: &offset_param
  $ref: '../../../openapi.yaml#/components/parameters/OffsetParam'
limit_param: &limit_param
  $ref: '../../../openapi.yaml#/components/parameters/LimitParam'
sort_param: &sort_param
  $ref: '../../../openapi.yaml#/components/parameters/SortParam'

not_found: &not_found
  $ref: '../../../openapi.yaml#/components/responses/NotFound'

tags: &tags
  - Product_Public

product_id: &product_id
  name: id
  in: path
  required: true
  description: ID of the product
  schema:
    type: integer
    example: 1
product_slug: &product_slug
  name: slug
  in: path
  required: true
  description: Slug of the product
  schema:
    type: string
    example: 'tai-nghe-1'

product_public: &product_public
  $ref: '../index.yaml#/components/schemas/ProductPublic'
# ============================================================

paths:
  /products/{id}:
    get:
      summary: Get product
      description: Retrieve a product by its ID.
      tags: *tags
      parameters: [*product_id]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta: *meta
                  data: *product_public
        '404': *not_found
  # ============================================================

  /products/{slug}:
    get:
      summary: Get product
      description: Retrieve a product by its slug.
      tags: *tags
      parameters: [*product_id, *product_slug]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta: *meta
                  data: *product_public
        '404': *not_found
  # ============================================================

  /products/{id}/related:
    get:
      summary: Get related products
      description: Retrieve a list of products related to the specified product.
      tags: *tags
      parameters: [*product_id, *offset_param, *limit_param, *sort_param]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta: *meta
                  data:
                    allOf:
                      - *infinite_scroll
                      - type: object
                        properties:
                          data:
                            type: array
                            items: *product_public
  # ============================================================

  /products:
    get:
      summary: Search products
      description: Retrieve a list of products based on search criteria.
      tags: *tags
      parameters:
        - *offset_param
        - *limit_param
        - *sort_param
        - name: query
          in: query
          description: Search keyword
          schema:
            type: string
            example: 'tai nghe'
        - name: category
          in: query
          description: Category ID of the products
          schema:
            type: integer
            example: 3
        - name: price_min
          in: query
          description: Minimum price of the products
          schema:
            type: integer
            example: 100000
        - name: price_max
          in: query
          description: Maximum price of the products
          schema:
            type: integer
            example: 500000
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta: *meta
                  data:
                    allOf:
                      - *infinite_scroll
                      - type: object
                        properties:
                          data:
                            type: array
                            items: *product_public
