required:
  - id
  - status
properties:
  id:
    type: integer
    description: 'Mã sản phẩm'
    example: 1001
  status:
    type: integer
    enum: [1, 2, 3, 4]
    example: 1
    description: >
      Trạng thái của sản phẩm:
        - **active** (1): Đang hoạt động và hiển thị
        - **out_of_stock** (2): Hết hàng
        - **inactive** (3): Tạm ngưng bán
        - **discontinued** (4): Ngừng sản xuất
