components:
  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      description: 'Auth token, ex: `admin` | `customer` | `Bearer <JWT>`'
      schema:
        type: string
        example: 'admin'

    IdempotencyKeyHeader:
      name: Idempotency-Key
      in: header
      required: false
      description: 'Key helper for recognize duplicate request (Idempotent)'
      schema:
        type: string
        example: 'oc8tKg1P2FV44hpj'
