type: object
properties:
  categories:
    type: array
    items:
      type: object
      properties:
        id: { type: integer, example: 1 }
        title: { type: string, example: 'Tai nghe' }
        slug: { type: string, example: 'tai-nghe' }
  tags:
    type: array
    items:
      type: object
      properties:
        id: { type: integer, example: 1 }
        name: { type: string, example: 'Hot_Trend' }
        slug: { type: string, example: 'hot-trend' }
  meta:
    type: array
    items:
      type: object
      properties:
        key: { type: string, example: 'color' }
        content: { type: string, example: 'red' }
