openapi: 3.1.0
info:
  title: Catalog Domain
  version: 1.0.0

paths:
  /products/{id}:
    $ref: './paths/products.yaml#/paths/~1products~1{id}'
  /products:
    $ref: './paths/products.yaml#/paths/~1products'

  /admin/products/{id}:
    $ref: './paths/admin_products.yaml#/paths/~1admin~1products~1{id}'
  /admin/products/{id}/status:
    $ref: './paths/admin_products.yaml#/paths/~1admin~1products~1{id}~1status'
  /admin/products:
    $ref: './paths/admin_products.yaml#/paths/~1admin~1products'
  /admin/products/{id}/inventories:
    $ref: './paths/admin_products.yaml#/paths/~1admin~1products~1{id}~1inventories'

  /categories:
    $ref: './paths/categories.yaml#/paths/~1categories'

  /admin/categories/{id}:
    $ref: './paths/admin_categories.yaml#/paths/~1admin~1categories~1{id}'
  /admin/categories:
    $ref: './paths/admin_categories.yaml#/paths/~1admin~1categories'

components:
  schemas:
    Product:
      $ref: './schemas/product.yaml#/schemas/Product'
    ProductPublic:
      $ref: './schemas/product.yaml#/schemas/ProductPublic'
    ProductBase:
      $ref: './schemas/product.yaml#/schemas/ProductBase'
    ProductStatus:
      $ref: './schemas/product.yaml#/schemas/ProductStatus'
    ProductAdjustInventory:
      $ref: './schemas/product.yaml#/schemas/ProductAdjustInventory'

    Category:
      $ref: './schemas/category.yaml#/schemas/Category'
    CategoryPublic:
      $ref: './schemas/category.yaml#/schemas/CategoryPublic'
    CategoryBase:
      $ref: './schemas/category.yaml#/schemas/CategoryBase'
