openapi: 3.1.0
info:
  title: Catalog Domain
  version: 1.0.0

paths:
  # @Product_Public
  /products/{id}:
    $ref: './paths/product.yaml#/paths/~1products~1{id}'
  /products/{slug}:
    $ref: './paths/product.yaml#/paths/~1products~1{slug}'
  /products/{id}/related:
    $ref: './paths/product.yaml#/paths/~1products~1{id}~1related'
  /products:
    $ref: './paths/product.yaml#/paths/~1products'
  # @Product_Admin
  /admin/products/{id}:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}'
  /admin/products/{id}/metas:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1metas'
  /admin/products/{id}/metas/{meta_id}:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1metas~1{meta_id}'
  /admin/products/{id}/categories:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1categories'
  /admin/products/{id}/tags:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1tags'
  /admin/products/{id}/status:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1status'
  /admin/products:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products'
  /admin/products/{id}/inventories:
    $ref: './paths/admin_product.yaml#/paths/~1admin~1products~1{id}~1inventories'
  # @Tag_Public
  /tags/{id}/products:
    $ref: './paths/tag.yaml#/paths/~1tags~1{id}~1products'
  # @Tag_Admin
  /admin/tags:
    $ref: './paths/admin_tag.yaml#/paths/~1admin~1tags'
  /admin/tags/{id}:
    $ref: './paths/admin_tag.yaml#/paths/~1admin~1tags~1{id}'
  # @Category_Public
  /categories:
    $ref: './paths/category.yaml#/paths/~1categories'
  /categories/{slug}:
    $ref: './paths/category.yaml#/paths/~1categories~1{slug}'
  /categories/{slug}/products:
    $ref: './paths/category.yaml#/paths/~1categories~1{slug}~1products'
  # @Category_Admin
  /admin/categories/{id}:
    $ref: './paths/admin_category.yaml#/paths/~1admin~1categories~1{id}'
  /admin/categories:
    $ref: './paths/admin_category.yaml#/paths/~1admin~1categories'
  
components:
  schemas:
    CategoryBase:
      $ref: './schemas/category.yaml#/CategoryBase'
    CategoryPublic:
      $ref: './schemas/category.yaml#/CategoryPublic'
    Category:
      $ref: './schemas/category.yaml#/Category'
    CategoryPublicHierarchy:
      $ref: './schemas/category.yaml#/CategoryPublicHierarchy'
    CategoryHierarchy:
      $ref: './schemas/category.yaml#/CategoryHierarchy'
    ProductBase:
      $ref: './schemas/product.yaml#/ProductBase'
    ProductPublic:
      $ref: './schemas/product.yaml#/ProductPublic'
    Product:
      $ref: './schemas/product.yaml#/Product'
    ProductMeta:
      $ref: './schemas/product.yaml#/ProductMeta'
    ProductExtra:
      $ref: './schemas/product.yaml#/ProductExtra'
    ProductPublicExtra:
      $ref: './schemas/product.yaml#/ProductPublicExtra'
    Tag:
      $ref: './schemas/tag.yaml#/Tag'

    UpdateCategoryRequest:
      $ref: './schemas/request.yaml#/UpdateCategoryRequest'
    UpdateProductStatusRequest:
      $ref: './schemas/request.yaml#/UpdateProductStatusRequest'
    AdjustProductInventoryRequest:
      $ref: './schemas/request.yaml#/AdjustProductInventoryRequest'
